### ISSUE TITLE
Onderzoeksvraag

### ISSUE THREAD

**Issue by Razpudding** [joordy/functional-programming#1]
- Hoe bepaal je wanneer iets een hogere auto is? Wat neem je als maatstaf voor SUvs?
- Wat bedoel je met divided correctly according to all users? Wie zijn de gebruikers, wat is correct en wat bedoel je met divided?
- Hoe ga je van Area ID naar stad? Mss kan je een dataset vinden met geolocaties van steden en dan kijen of de locatie in die stad valt?
- Hoe kom je aan data van aantal inwoners per stad?
- Ik zou per deelvraag de variabelen aangeven die je denkt nodig te hebben. Nu weet ik niet bij welke vraag je ChargingPointCapacity nodig denkt te hebben.

**Comment by joordy** [comment]
Dankjewel voor de feedback! Ik heb het direct even aangepast,
