### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by veerleprins** [joordy/functional-programming#4]
### Repo + ReadMe:
**Tops:** 👍 
- There is a .gitignore and there are no node modules or other junk in your repository
- A clear description of the repository has been made.
- Concept is indicated in your ReadMe, but not expanded because you are referring to your wiki.
- Your ReadMe neatly lists the sources you used.

**Tips:** ❗ 
- Perhaps you can mention something about the Volkskrant data in the description, since you have already worked with this a little bit.
- You have not yet linked to the most interesting functional pattern in your ReadMe.
- You have not yet described in your ReadMe what you have done with the invalid / empty values.
- I would just change the point 'bronnen' to 'resources' in your ReadMe as the rest of your ReadMe & Repo are written in English.

### Wiki
**Tops:** 👍 
- A debriefing has been described.
- There is a description to read about cleaning the data.

** Tips:** ❗ 
- You did not really describe your process when cleaning your data. It only says what you ultimately did, but what went wrong in the meantime? Or did nothing go wrong?
- The same file also contains 'lorem ipsum' text, which might be useful to remove for the assessment.

### Code (Survey data)
**Tops:** 👍 
- The most important code is at the top.
- You have made good use of the .map () methods (not using a forEach).
- Nice that you clean up several columns.

**Tips:** ❗ 
- On line 61 you use a normal function within your .map while you do this further with the other .map with an arrow functions. Maybe you can draw 1 line here by making it consistent :).

**Comment by joordy** [comment]
Hi Veerle! Thanks for the feedback, I will use your feedback to improve my repository!
